print ("saba")
print("bolkvadze")
print(15)
print(str(10)+" klasi")
print("xulo")
print("nika")
print("luka")
print("saba")
print("gio")
print("dachi")
print("zuka")
print("mate")
print("lashagiorgi")
print("lasha")
print("avto")
print("svarchika makkvala")
print("fasanauris xinkali")
print("pizza")
print("anzori")
print("jemali")